export default {
  command: ['menu', 'vinic'],
  handler: async (m, { conn, prefix, pushname }) => {
    try {
      // Define menu sections for organization
      const menuSections = {
        header: {
          title: '☘ 𝗞𝗘𝗩𝗜𝗡 𝗧𝗘𝗖𝗛 ☘',
          content: [
            `👤 ᴏᴡɴᴇʀ: ☘ ᴋᴇʟᴠɪɴ ᴛᴇᴄʜ ☘`,
            `👤 ᴜsᴇʀ: ${pushname || 'Unknown'}`,
            `🤖 ʙᴏᴛɴᴀᴍᴇ: ᴠɪɴɪᴄ xᴍᴅ`,
            `🌍 ᴍᴏᴅᴇ: ${conn.public ? 'ᴘᴜʙʟɪᴄ' : 'ᴘʀɪᴠᴀᴛᴇ'}`,
            `🛠️ ᴘʀᴇғɪx: [ ${prefix} ]`,
            `📈 ᴄᴍᴅs: 100+`, // Replace with actual command count if available
            `🧪 ᴠᴇʀsɪᴏɴ: 1.0.0-beta`,
          ],
        },
        bug: {
          title: '> 𝗕𝗨𝗚 𝗠𝗘𝗡𝗨 ',
          commands: [
            '𝖨𝗇𝗏𝗂𝗌',
            '𝖷𝖼𝗋𝖺𝗌𝗁',
            '𝖢𝗋𝖺𝗌𝗁',
            '𝖣𝖾𝗅𝖺𝗒',
            '𝙲𝚛𝚊𝚡',
            '𝖣𝖾𝗅𝖺𝗒𝖼𝗈𝗆𝖻𝗈',
            '𝖣𝖺𝗋𝗄',
            '𝖣𝗂𝗆',
            'Vinic-crash',
          ],
        },
        owner: {
          title: '> 𝗢𝗪𝗡𝗘𝗥 𝗠𝗘𝗡𝗨 ',
          commands: [
            '𝖠𝖽𝖽𝗉𝗋𝖾𝗆 <number>',
            '𝖣𝖾𝗅𝗉𝗋𝖾𝗆 <number>',
            '𝖯𝗎𝖻𝗅𝗂𝖼',
            'private',
            '𝙸𝚍𝚌𝚑',
            '𝙲𝚛𝚎𝚊𝚝𝚎𝚌𝚑',
            'antidelete',
            'delete',
            'setpp',
            'lastseen',
            'groupid',
            'reportbug',
            'listblocked',
            'online',
            'join',
            'leave',
            'setbio',
            'reqeust',
            'block',
            'toviewonce',
            'autoviewstatus',
            'unblock',
            'unblockall',
            'anticall',
            'antibug',
            'vv',
            'idch',
            'autorecording',
            'autotyping',
            'getpp',
          ],
        },
        group: {
          title: '> 𝗚𝗥𝗢𝗨𝗣 𝗠𝗘𝗡𝗨 ',
          commands: [
            '𝖧𝗂𝖽𝖾𝗍𝖺𝗀',
            '𝖪𝗂𝖼𝗄',
            '𝖱𝖾𝗌𝖾𝗍𝗅𝗂𝗇𝗄',
            'linkgc',
            'checkchan',
            'antilink',
            'listonline',
            'add',
            'listactive',
            'listinactive',
            'close',
            'open',
            'kick',
            'closetime',
            'disappear',
            'opentime',
            'poll',
            'totalmembers',
            'mediatag',
            'getgrouppp',
            'antilink',
            'tagall',
            'tagadmin',
            'setgroupname',
            'delgrouppp',
            'invite',
            'editinfo',
            'promote',
            'demote',
            'setdisc',
          ],
        },
        download: {
          title: '> 𝗗𝗢𝗪𝗡𝗟𝗢𝗔𝗗 𝗠𝗘𝗡𝗨 ',
          commands: [
            'play',
            'play2',
            'song',
            'gitclone',
            'mediafire',
            'ytmp4',}, { quoted: m });
  }
};

export default menu;
